FROM jptmoore/core-export-service-aarch64:v0.0.1

EXPOSE 8080

LABEL databox.type="export-service"

RUN addgroup -S databox && adduser -S -g databox databox && \
chown -R databox:databox /home/databox

USER databox

WORKDIR /home/databox

CMD ["/home/databox/service.exe"]
