FROM jptmoore/alpine-baseimage-aarch64

USER databox
RUN sudo apk add libffi-dev libressl-dev
RUN opam remove ezirmin irmin re.1.7.1
RUN opam pin add -n opium https://github.com/me-box/opium.git#term-argv
RUN opam install -y opium websocket-lwt depyt cohttp

# add the code
ADD src src
RUN sudo chown -R databox:nogroup src

# add the build script
ADD build.sh .

# setup ocaml
RUN sudo chmod +x build.sh && sync \
&& ./build.sh \
&& rm -rf /home/databox/src \
&& rm -rf /home/databox/.opam \
&& rm -rf /home/databox/opam-repository \
&& sudo apk del .build-deps

FROM resin/aarch64-alpine:3.5

USER root
WORKDIR /home/databox/

COPY --from=0 /home/databox/ .
# runtime dependencies
RUN apk update && apk upgrade \
&& apk add libsodium gmp zlib libzmq

EXPOSE 8080

LABEL databox.type="export-service"

CMD ["./service.exe", "-v"]
